### PR TITLE
Services/issues

### PR DESCRIPTION
**Pull request by ghost**
I've included the `PullRequest` type attribute into the `Issue` resource, which was missing in my previous pull request.

### CODE REVIEW

**Comment by toutouastro** [comment]
remove issues from TODO list

**Comment by ghost** [comment]
@toutouastro thanks for pointing that out.

**Comment by copitux** [comment]
Shit. I merged it into service/issues from a manual pull into my local repo. A fix it ASAP ;)

**Comment by ghost** [comment]
I also can rebase the commits on top of `develop`, let me know.

**Comment by copitux** [comment]
I merged all your changes by hand. Thanks for all your efforts and support ;)

**Comment by ghost** [comment]
You're welcome!

**Pull request closed without merging**
