### PR TITLE
Issues service

### PR DESCRIPTION
**Pull request by ghost**
Like I wrote in the previous pull request I've continued working after @conorbranagan's commits. I've added the `Label` and `Milestone` services into `Issues`.

### CODE REVIEW

**Comment by ghost** [comment]
Docs added in d3d583d.

**Comment by ghost** [comment]
I've noticed that you've merged the pull requests service implementation. This service needs update because an issue can be related to a pull request. 

I'm closing this pull request and sending another one as soon as it's ready.

**Comment by copitux** [comment]
Thank you very much for your work. I'm reviewing the pull requests in order when I get free time, but I'm actually overwhelmed.

You could push commits to your 'alejandrogomez:services/issues' branch and reopen the pull requests, if you want.

**Comment by ghost** [comment]
No rush. I'm pushing commits to my topic branch and sending a pull request as soon as is ready for review. 

Thank you for your time.

**Pull request closed without merging**
